
version: '3'
 
services:
  db:
    image: mysql:latest
    container_name: db_laravel
    environment:
      MYSQL_ROOT_PASSWORD: 3636
      MYSQL_DATABASE: laravel
      MYSQL_USER: gian
      MYSQL_PASSWORD: 3636
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma_laravel
    links:
      - db
    environment:
      PMA_HOST: db_laravel
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80
volumes:
  dbdata:
